apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- role.yaml
- rolebinding.yaml
- webhook.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml