apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- crds
- "base.yaml"

commonLabels:
    application: "cert-manager"

images:
- name: quay.io/jetstack/cert-manager-webhook
  newName: quay.io/jetstack/cert-manager-webhook
  newTag: v1.5.4
- name: quay.io/jetstack/cert-manager-controller
  newName: quay.io/jetstack/cert-manager-webhook
  newTag: v1.5.4
- name: quay.io/jetstack/cert-manager-cainjector
  newName: quay.io/jetstack/cert-manager-webhook
  newTag: v1.5.4
